### ISSUE TITLE
Styles can not be opened

### ISSUE THREAD

**Issue by darksmoke** [fabric-bolt/fabric-bolt#123]
good afternoon
The server starts
fabric-bolt --config = / home / darksmoke / .fabric-bolt / settings.py runserver
The browser opens, and then the error:
"NetworkError: 404 NOT FOUND - http://127.0.0.1:8000/static/css/flatly.min.css"
Styles can not be opened, how to fix this error?

**Comment by jproffitt** [comment]
If you want to use the built in django server to serve the static files, you need to put `DEBUG = True` in your settings file. However, it is not recommended to use the django server for production environments.
