### ISSUE TITLE
Migration not working

### ISSUE THREAD

**Issue by freezlite** [fabric-bolt/fabric-bolt#131]
I'm using fabric-bolt migrate 
django.db.utils.ProgrammingError: (1146, "Table 'fabric-bolt.south_migrationhistory' doesn't exist")

**Comment by freezlite** [comment]
Ok, I understood. Just add fabric-bolt syncdb to readme

**Comment by freezlite** [comment]
Another issue 
Error found during dry run of '0005_auto__add_field_stage_project'! Aborting.
ValueError: The database backend does not accept 0 as a value for AutoField.
For mysql driver.

**Comment by jproffitt** [comment]
What version of fabric-bolt do you have installed? We no longer use south since we upgraded to django 1.7.

**Comment by pikhovkin** [comment]
Run `fabric-bolt syncdb` before `fabric-bolt migrate`

**Comment by npardington** [comment]
Yeah since updating I haven't had problems running the migrations. If you could try updating that would be great. We'll open the ticket again if you're still having problems.

**Comment by jproffitt** [comment]
There was one left over south migration which has since been removed, so all should be good now. You may need to `pip uninstall south` if you have any more issues.
