### ISSUE TITLE
In progress deploy is restarted when navigating

### ISSUE THREAD

**Issue by msurdi** [fabric-bolt/fabric-bolt#134]
I've noticed that after a deployment is in progress, if you navigate back to any other part of the UI, when you come back to watch the progress, the deployment is restarted from scratch, leaving the previous one unfinished.

It seems that the problem is that the DeploymentOutputStream view, which is used by the iframe showing the output is creating a new deployment process each time.

**Comment by msurdi** [comment]
Would it make sense to move the deployment task to a uWSGI spooler task?

The task could write lines as they come to a new DeploymentOutput model, which belongs to a Deployment.

Then the StreamingHttpResponse could yield from DeploymentOutput(s) until the Deployment is set to either success or failed. Same with the Websockets implementation.

Does this make sense for you? If yes, probably I could find some time to work on this as it is major issue for us.

**Comment by christophervalles** [comment]
👍 on this bug

We are experiencing the same issue. If we move away from the progress screen to come back again a new deployment process is created leaving the old one in the limbo. After a while, the server is full of processes laying over there doing nothing.

**Comment by dimov-cz** [comment]
+
