### ISSUE TITLE
Files App

### ISSUE THREAD

**Issue by npardington** [fabric-bolt/fabric-bolt#173]
# Files
A place to talk about the work going on at [https://github.com/qiulin/fabric-bolt/commit/a2b39a9abf1db4fa384cb79c7a1a23c98b79315d](https://github.com/qiulin/fabric-bolt/commit/a2b39a9abf1db4fa384cb79c7a1a23c98b79315d)

**Comment by qiulin** [comment]
I'm working on more convenient deloyment. In such situation, without a  files app, I have to provide a another seperate way to upload some necessary files.

**Comment by npardington** [comment]
Hopefully it will be something others could benefit from. Let us know if you ever want to bounce ideas around.
