### ISSUE TITLE
Q: project repo available to fabfile?

### ISSUE THREAD

**Issue by nanuxbe** [fabric-bolt/fabric-bolt#178]
Hi,

this project is quite new to me and looks very exciting. Great job, this looks like what I've been looking for for a while now.
I've successfully installed fabric-bolt and deployed a project with it.
Now I am trying to build a custom fabfile which would initialize the project on the host if the project doesn't exist there yet. In order to do that I need to have access to the project's repo_url (to do the iitial clone). I cannot find it in the env. Am I missing something or is the repo_url not available from inside the fabfile?

Cheers,
Emma

**Comment by npardington** [comment]
Hey Emma, 

Thanks for the interest in the project. It's exciting to know you've been able to run a deployment. 

As to your issue, we don't currently add the repo url automatically to the env variable in Fabric. However, you can use a project configuration to accomplish what you're after.

Here's a screen shot

![screen shot 2015-10-01 at 8 47 27 pm](https://cloud.githubusercontent.com/assets/2708258/10237300/ecb8dc10-687d-11e5-82ba-30a1afd15a0a.png)

Notice that there are project & stage configurations. If you define repo_url on a project & then again on a stage it will be overridden by what's defined on the stage.

Let us know if we can help further.

**Comment by nanuxbe** [comment]
Hi Nathaniel,

thanks for the answer, this will help me get started with what I want to do! :smile:
