### ISSUE TITLE
Fatal error: Couldn't find any fabfiles! when running task

### ISSUE THREAD

**Issue by ylebon** [fabric-bolt/fabric-bolt#53]
On windows, when running a task i got the following error:

Fatal error: Couldn't find any fabfiles! 

Remember that -f can be used to specify fabfile path, and use -h for help. 

Aborting.

**Comment by leongaban** [comment]
Hi, I'm running into this same problem... in regards to using `-f` to specify a fabfile path, how do I find out which fabfile and how do I get that path?

**Comment by jproffitt** [comment]
You can set the fabfile path in your config file using the `FABFILE_PATH` setting. Does that not work for you?

**Comment by leongaban** [comment]
I was in the wrong project directory, thought I could have run that script anywhere. Don't know how or where the fabfile config is, I'm the frontend developer.
